Repository learn-opensource/dumping-dsa, pull requests merged in 2022-10, with the labels that each got.

#1 Added hello
  leetcode/hello_world.py
Labels: hacktoberfest

#2 Added solution of implementing linked list in C++
  leetcode/linked_list.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#6 task4
  leetcode/Leap_year.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#4 task2
  leetcode/Pascal_traiangle.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#11 commit
  GCD.java
  mulmatrices.java
  standard.java
  transpose.java
Labels: hacktoberfest, hacktoberfest-accepted

#9 Linear_search Problem
  leetcode/linear_search.py
  leetcode/traversing_linked_list.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#8 SimpleCalculatorusingJAVA
  .vscode/settings.json
  CALCULATOR USING HTML CSS JS/INDEX.html
  CALCULATOR USING HTML CSS JS/script.js
  CALCULATOR USING HTML CSS JS/style.css
  calculator.java
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#12 Kartik 169
  palindrome.java
  sandard.java
Labels: hacktoberfest, hacktoberfest-accepted

#16 1st commit
  leetcode/Login_page/app.js
  leetcode/Login_page/index.html
  leetcode/Login_page/style.css
  leetcode/degreeConversion.js
  leetcode/swaptonun.js
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#15 Merge_sort
  leetcode/merge_sort.py
Labels: hacktoberfest, hacktoberfest-accepted

#14 insertion
  leetcode/insertion.py
Labels: hacktoberfest, hacktoberfest-accepted

#13 bubble_sorting
  leetcode/sorting.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#18 FactroialOfNo_commit
  leetcode/FactroialOfGivenNo.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#17 created twosum.py
  leetcode/twosum.py
Labels: hacktoberfest, hacktoberfest-accepted

#19 Adding an Algorith in python
  leetcode/jumpsearch.py
Labels: hacktoberfest, hacktoberfest-accepted
